forwards:
  - source: -1001498678985
    dest: [-1001788528281,5231326048]
    offset: 0
past:
  delay: 3

plugins:
  # specify the plugins you want to use
  filter:
    text:
      blacklist: ["badword"]
